### PR TITLE
Apply clearfix styling directly on css definitions and remove vf__cf where used.

### LINKED ISSUE #86: vf__optional and vf__required elements do not contain the CSS clearfix
### Expected behavior

Proper aligning of elements

### Actual behavior

When a field label is long (in this case the label of a boolean field), it doesn't properly wrap the contents, the layout gets distorted.

### Steps to reproduce the behavior and a code example

```php
// Code example to reproduce this issue
$form->addField('bools', 'Check me before continuing', ValidForm::VFORM_BOOLEAN, ['required' => true], ['required' => 'This is so required.']);
```

### Which version/branch of ValidForm Builder do you use?

I use version/branch: `master`

### Suggested solution
Apply the already available styling for the `.vf__cf` css selector to `.vf__optional` and `.vf__required` as well by default.

This could however potentially break/alter layouts.

### PR DESCRIPTION
**Pull request by rvanbaalen**
This fixes #86 

## Before:

screenshot 2017-07-10 10 22 12

screenshot 2017-07-10 10 23 19

## After:

screenshot 2017-07-10 10 23 57

screenshot 2017-07-10 10 24 02

### CODE REVIEW

**Comment by flangfeldt** [comment]
I would have chosen to add the vf__cf class to the divs that have the vf__optional and vf__required classes. That way it's still modular. 

The idea is that you can stack behavior of HTML elements with multiple classes. 
You just decided that all vf__required and vf__optional classed elements have the clear fix. What if I have a situation were a clearfix breaks something in my element that I have marked as required? How do I remove the clearfix? While using a class, I can just remove it from the element. But with your solution I need to create a vf__nocf class and add it to the element. Not ideal, right?

**Comment by rvanbaalen** [comment]
I dont want to stack up a sht load of classes of its not needed. Bloats the generated dom structure. If you need to customize things go ahead drop vfb default css and go crazy. 

I get the modular approach but I dont really agree in this particular case. Its a style fix for the default layout of vfb, not an added feature. 

Your call :-)

---
This email was sent from my iPhone and therefore subject to typos and other inaccuracies.

**Comment by flangfeldt** [comment]
I get your point and agree that the clearfix is pretty much mandatory for the correct styling of the labels, but I don't like the inconsistency.

Either we have a clearfix class and add it to elements that need it or we apply the clearflix styling to all classes that need it. Not 50/50.

If we go for your solution I want it added to all other classes that use the vf__cf class at the moment. Looks like the vf__dynamic, vf__navigation, vf__pagenavigation and vf__multifield classes are candidates.

**Comment by rvanbaalen** [comment]
Will update the PR to add clearfix to mentioned classes. Hang in there :-)

---
This email was sent from my iPhone and therefore subject to typos and other inaccuracies.

**Comment by flangfeldt** [comment]
Please verify if these are in fact the correct and only classes. I only did a quick search.

**Comment by rvanbaalen** [comment]
Will do. 

---
This email was sent from my iPhone and therefore subject to typos and other inaccuracies.

**Comment by rvanbaalen** [comment]
@flangfeldt Here you go. Please review :-)

**Comment by rvanbaalen** [comment]
For legacy sake I left the `.vf__cf` css definition in there even though it's not being used by the library anymore.

**Comment by flangfeldt** [comment]
Yes, somebody might use vf__cf for something else.

**Pull request merged**
