### PR TITLE
Make elementAsHtml methods public

### LINKED ISSUE #72: ValidForm methods should be made protected instead of private
### Expected behavior

I expected that a user would be able to write his own `valuesAsHtml` logic by extending `ValidForm` and overwriting the involved methods. As discussed in #64

### Actual behavior

`areaAsHtml` [L1479](https://github.com/neverwoods/validformbuilder/blob/master/classes/ValidFormBuilder/ValidForm.php#L1479), `multiFieldAsHtml` [L1548](https://github.com/neverwoods/validformbuilder/blob/master/classes/ValidFormBuilder/ValidForm.php#L1548) and `fieldAsHtml` [L1609](https://github.com/neverwoods/validformbuilder/blob/master/classes/ValidFormBuilder/ValidForm.php#L1609) are private methods which disables the ability to extend and overwrite these methods.

### Which version/branch of ValidForm Builder do you use?

I use version/branch: `master`

### Suggested solution

I suggest we change the method's visibility to at least `protected` or perhaps even `public`, just like `fieldsetAsHtml` [L1395](https://github.com/neverwoods/validformbuilder/blob/master/classes/ValidFormBuilder/ValidForm.php#L1395).

### PR DESCRIPTION
**Pull request by rvanbaalen**
Enables extendablility of ValidForm Builder

Fixes #72

### CODE REVIEW

**Comment by rvanbaalen** [comment]
@flangfeldt Can you merge this in? It allows users to modify ValidForm behaviour by extending the class, which we advertise to do.

**Comment by rvanbaalen** [comment]
@flangfeldt Any update on this?

**Comment by rvanbaalen** [comment]
@flangfeldt I'm going to veto this one by the end of the week :-)

**Comment by flangfeldt** [comment]
Why make the methods public? They are internal, so protected should be enough, right?

**Comment by rvanbaalen** [comment]
Making them public allows for more hacking and customisation in custom-made classes or use cases. There's nothing against these methods being public, right?

**Comment by flangfeldt** [comment]
When I think of "extendability" I think mostly of inheritance. Protected methods are perfect for that. I want to prevent the API to get cluttered because we were lazy and just "made everything public". These methods are important for the inner workings of ValidForm Builder and their visibility reflects that. 

Do you have a good use case where these methods require public visibility?

**Comment by rvanbaalen** [comment]
Lets stick with `protected` visibility for now.

**Pull request merged**
