### PR TITLE
Work In Progress - ValidForm Builder 4.0

### PR DESCRIPTION
**Pull request by rvanbaalen**
We will be discussing new features, fixes, (breaking) changes and other relative information regarding the upcoming 4.0 release of ValidForm Builder in this pull request.
### Tests
- [ ] Write unit tests
### General
- [ ] Differentiate between field type and validation type (#18)
- [ ] Redesign method signatures (kill the many parameters, make it PHP strict mode compatible, see #5)
- [ ] Make field types extendible to allow users to easily create custom field types
- [ ] Research how Composer and Bower can work together to easily install both client-side and server-side code base
- [ ] Every field type (select, textarea, input[type='password'], anything) should be able to implement custom validation rules
- [ ] Be completely HTML5 compliant
  - [ ] Create a ValidForm Compatibility Package to support older browsers (a collection of HTML5 shims)
### Code clean-up
- [ ] Clean-up field classes
  - [ ] HTML code
  - [ ] Get rid of [ClassDynamic](https://github.com/neverwoods/validformbuilder/blob/master/classes/ValidFormBuilder/ClassDynamic.php)
  - [ ] Clean up `toHtml` logic
  - [ ] All code should be [PSR-2 compatible](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md)
### Website
- [ ] Update the website after 4.0 release
  - [ ] Home
  - [ ] Docs
  - [ ] Tutorials
  - [ ] Examples

### CODE REVIEW

**Comment by rvanbaalen** [comment]
@flangfeldt I guess we should get rid of this pull request and start over when we're planning a new big major release.

**Comment by rvanbaalen** [comment]
Closing this. @flangfeldt We should make a 5.* PR and copy some of these items there.

**Comment by flangfeldt** [comment]
Why close it to start something new with the same context? I don't think we actually wrote any code in this, did we?

**Comment by rvanbaalen** [comment]
We're beyond the 4.0 point for a while now and some of these issues have been handled again. Also, there's a ton of commits linked here that are unrelated that's why I propose to start with a new PR.

**Comment by flangfeldt** [comment]
Alright. Let's move on. 5.0 here we come!

**Pull request closed without merging**
